### ISSUE TITLE
App backscaling client throws panic

### ISSUE THREAD

**Issue by Danil-Grigorev** [konveyor/mig-controller#506]
During testing there was discovered and issue with client type casting:
```
{"level":"info","ts":1587406478.6430786,"logger":"discovery|vxspf","msg":"Pod updated.","meta":{"PK":"e13ff4f3af8482151b092d38134ab72527ed9da9","UID":"b310cb06-7abc-4c45-9393-9891a4c86bca","Version":1869477,"Namespace":"openshift-migration","Name":"registry-802065ca-2cc4-4f9b-aab3-714be6987fa4-9p269-1-deploy"}}
E0420 20:14:38.814093   84579 runtime.go:69] Observed a panic: &runtime.TypeAssertionError{_interface:(*runtime._type)(0x1a78b40), concrete:(*runtime._type)(0x1bcc600), asserted:(*runtime._type)(0x1c00b40), missingMethod:""} (interface conversion: client.Client is *compat.Client, not compat.Client)
/home/dgrigore/go/src/github.com/konveyor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:76
/home/dgrigore/go/src/github.com/konveyor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/home/dgrigore/go/src/github.com/konveyor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/lib/golang/src/runtime/panic.go:679
/usr/lib/golang/src/runtime/iface.go:255
/usr/lib/golang/src/runtime/iface.go:265
/home/dgrigore/go/src/github.com/konveyor/mig-controller/pkg/controller/migplan/gvk.go:52
/home/dgrigore/go/src/github.com/konveyor/mig-controller/pkg/controller/migplan/gvk.go:18
/home/dgrigore/go/src/github.com/konveyor/mig-controller/pkg/controller/migplan/validation.go:221
/home/dgrigore/go/src/github.com/konveyor/mig-controller/pkg/controller/migplan/migplan_controller.go:215
/home/dgrigore/go/src/github.com/konveyor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215
/home/dgrigore/go/src/github.com/konveyor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158
/home/dgrigore/go/src/github.com/konveyor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/home/dgrigore/go/src/github.com/konveyor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/home/dgrigore/go/src/github.com/konveyor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/usr/lib/golang/src/runtime/asm_amd64.s:1357
panic: interface conversion: client.Client is *compat.Client, not compat.Client [recovered]
	panic: interface conversion: client.Client is *compat.Client, not compat.Client

goroutine 512 [running]:
github.com/konveyor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/dgrigore/go/src/github.com/konveyor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x105
panic(0x1a05420, 0xc006e83590)
	/usr/lib/golang/src/runtime/panic.go:679 +0x1b2
github.com/konveyor/mig-controller/pkg/controller/migplan.ReconcileMigPlan.newGVKCompare(0x1fc8120, 0xc0006ded50, 0xc00029eee0, 0xc00e99c1e0, 0xc00e99c300, 0x1c5218b, 0x9)
	/home/dgrigore/go/src/github.com/konveyor/mig-controller/pkg/controller/migplan/gvk.go:52 +0x9cb
github.com/konveyor/mig-controller/pkg/controller/migplan.ReconcileMigPlan.compareGVK(0x1fc8120, 0xc0006ded50, 0xc00029eee0, 0xc00e99c1e0, 0x0, 0x0)
	/home/dgrigore/go/src/github.com/konveyor/mig-controller/pkg/controller/migplan/gvk.go:18 +0xdd
github.com/konveyor/mig-controller/pkg/controller/migplan.ReconcileMigPlan.validate(0x1fc8120, 0xc0006ded50, 0xc00029eee0, 0xc00e99c1e0, 0x0, 0xc00ed1794c)
	/home/dgrigore/go/src/github.com/konveyor/mig-controller/pkg/controller/migplan/validation.go:221 +0x358
github.com/konveyor/mig-controller/pkg/controller/migplan.(*ReconcileMigPlan).Reconcile(0xc0005ff880, 0xc00ed81020, 0x13, 0xc00ed1794c, 0x3, 0xc001222600, 0x0, 0x0, 0x0)
	/home/dgrigore/go/src/github.com/konveyor/mig-controller/pkg/controller/migplan/migplan_controller.go:215 +0x3a0
github.com/konveyor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0005010e0, 0x1000000000000)
	/home/dgrigore/go/src/github.com/konveyor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215 +0x20a
github.com/konveyor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1()
	/home/dgrigore/go/src/github.com/konveyor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158 +0x36
github.com/konveyor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0074f24a0)
	/home/dgrigore/go/src/github.com/konveyor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x5e
github.com/konveyor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0074f24a0, 0x3b9aca00, 0x0, 0x1, 0xc00004e1e0)
	/home/dgrigore/go/src/github.com/konveyor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xf8
github.com/konveyor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc0074f24a0, 0x3b9aca00, 0xc00004e1e0)
	/home/dgrigore/go/src/github.com/konveyor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/konveyor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
	/home/dgrigore/go/src/github.com/konveyor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:157 +0x32e
exit status 2
make: *** [Makefile:21: run] Error 1
```

**Comment by djwhatle** [comment]
@Danil-Grigorev can you provide some context on what leads to this error occurring? I want to make sure we have enough information to know that we've solved this bug.

1) Which OCP cluster versions were involved that generated the trace above?
2) Any other reproducer instructions? Does this occur on startup, how can I trigger this?

Thank you for providing the trace, that is helpful!

**Comment by Danil-Grigorev** [comment]
Thats an issue i was not able to fix, as my pr was reverted before me returning back to it. The type casting was simply wrong, as the return value of the NewClient was not using a new compat client.

**Comment by Danil-Grigorev** [comment]
Creating a plan is enough
