### ISSUE TITLE
MigPlan controller panics if a bad MigClusterRef is introduced to MigPlan

### ISSUE THREAD

**Issue by djwhatle** [konveyor/mig-controller#999]
**Describe the bug**
MigPlan controller crashloops the controller if you introduce a bad DestClusterRef. 

```
goroutine 528 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/Users/dwhatley/code/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181127025237-2b1284ed4c93/pkg/util/runtime/runtime.go:58 +0x105
panic(0x5b2da20, 0x739dd90)
	/Users/dwhatley/pkg/go1.14.4/src/runtime/panic.go:969 +0x166
github.com/konveyor/mig-controller/pkg/apis/migration/v1alpha1.(*MigCluster).BuildRestConfig(0x0, 0x63254e0, 0xc002554b10, 0x4019b73, 0xc002554b10, 0xc002561868)
	/Users/dwhatley/code/go/src/github.com/konveyor/mig-controller/pkg/apis/migration/v1alpha1/migcluster_types.go:259 +0x37
github.com/konveyor/mig-controller/pkg/apis/migration/v1alpha1.(*MigCluster).GetClient(0x0, 0x63254e0, 0xc002554b10, 0x5dce2a0, 0xc002554b10, 0xc002561868, 0xc002554b10)
	/Users/dwhatley/code/go/src/github.com/konveyor/mig-controller/pkg/apis/migration/v1alpha1/migcluster_types.go:151 +0x43
github.com/konveyor/mig-controller/pkg/apis/migration/v1alpha1.(*MigCluster).GetClusterSubdomain(0x0, 0x63254e0, 0xc002554b10, 0xc002554b10, 0x0, 0x0, 0x5)
	/Users/dwhatley/code/go/src/github.com/konveyor/mig-controller/pkg/apis/migration/v1alpha1/migcluster_types.go:208 +0x43
github.com/konveyor/mig-controller/pkg/controller/migplan.ReconcileMigPlan.validateNamespaceLengthForDVM(0x6324760, 0xc00051fb30, 0x6313f00, 0xc0005e0700, 0xc0002c0b60, 0xc00253e6c0, 0xc00051fb30, 0x6313f00, 0xc0005e0700)
	/Users/dwhatley/code/go/src/github.com/konveyor/mig-controller/pkg/controller/migplan/validation.go:290 +0x121
github.com/konveyor/mig-controller/pkg/controller/migplan.ReconcileMigPlan.validateNamespaces(0x6324760, 0xc00051fb30, 0x6313f00, 0xc0005e0700, 0xc0002c0b60, 0xc00253e6c0, 0x0, 0x0)
	/Users/dwhatley/code/go/src/github.com/konveyor/mig-controller/pkg/controller/migplan/validation.go:265 +0x8e
github.com/konveyor/mig-controller/pkg/controller/migplan.ReconcileMigPlan.validate(0x6324760, 0xc00051fb30, 0x6313f00, 0xc0005e0700, 0xc0002c0b60, 0xc00253e6c0, 0x8, 0x62d6240)
	/Users/dwhatley/code/go/src/github.com/konveyor/mig-controller/pkg/controller/migplan/validation.go:136 +0x10a
github.com/konveyor/mig-controller/pkg/controller/migplan.(*ReconcileMigPlan).Reconcile(0xc000233260, 0xc00027b060, 0x13, 0xc000b51e58, 0x8, 0x0, 0x0, 0x0, 0x0)
	/Users/dwhatley/code/go/src/github.com/konveyor/mig-controller/pkg/controller/migplan/migplan_controller.go:250 +0x508
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0000d5040, 0x0)
	/Users/dwhatley/code/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.11/pkg/internal/controller/controller.go:215 +0x1d6
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1()
	/Users/dwhatley/code/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.11/pkg/internal/controller/controller.go:158 +0x36
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0005adeb0)
	/Users/dwhatley/code/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181127025237-2b1284ed4c93/pkg/util/wait/wait.go:133 +0x5f
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0005adeb0, 0x3b9aca00, 0x0, 0x1, 0xc0001480c0)
	/Users/dwhatley/code/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181127025237-2b1284ed4c93/pkg/util/wait/wait.go:134 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc0005adeb0, 0x3b9aca00, 0xc0001480c0)
	/Users/dwhatley/code/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181127025237-2b1284ed4c93/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
	/Users/dwhatley/code/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.11/pkg/internal/controller/controller.go:157 +0x2fd
```

**Comment by djwhatle** [comment]
I have been staring at the screen too long, wrong controller.
